### ISSUE TITLE
Can you share setting in cifar100? Experiment of GCE+SR not work in this code.

### ISSUE THREAD

**Issue by clearlovewl** [hitcszx/lnl_sr#2]
Can you share setting in cifar100? Experiment of GCE+SR not work in this code.

**Comment by hitcszx** [comment]
Dear Sir or Madam:
Thanks for your issue. The parameter setting of CIFAR-100 is tau=0.5, p=0.01, rho=1.02, freq=1, and lamb is set 4 and 10 for symmetric noise and asymmetric noise, respectively. For GCE+SR, we set q=0.001. We found that there is a bug in the setting of lamb on CIFAR-100, and we have fixed it. Please try it again.
